version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  notification-service:
    build: notification-service
    ports:
      - "3001:3001"
    environment:
      - BROKER_URI=amqp://guest:guest@rabbitmq:5672
      - QUEUE_NAME=user_queue
      - PORT=3001
    depends_on:
      rabbitmq:
        condition: service_healthy

  user-service:
    build: user-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/magmamath1
      - BROKER_URI=amqp://guest:guest@rabbitmq:5672
      - QUEUE_NAME=user_queue
      - PORT=3000
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
  mongodb_data: 